# https://cert-manager.io/docs/configuration/selfsigned/
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "wazuh.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "wazuh.fullname" . }}-root-ca
spec:
  isCA: true
  secretName: root-secret
  commonName: root-ca
  subject:
    organizations:
      - Company
    countries:
      - US
    localities:
      - California
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 87600h # 3650d
  issuerRef:
    name: {{ include "wazuh.fullname" . }}-selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "wazuh.fullname" . }}-ca-issuer
spec:
  ca:
    secretName: root-secret