#TODO
# - Make it optional
# - Analyze traffic and add default rules
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer
spec:
  selector:
    matchLabels:
      app: {{ include "wazuh.fullname" . }}-indexer
  minAvailable: 1